#!/usr/bin/env bash

ROOT=$(pwd)

git submodule update --init --recursive
sudo apt install libglfw3-dev libglew-dev libstb-dev

pushd imgui
git fetch origin
git checkout 9fdeb41e
git checkout -b imgui-9fdeb41e
git am $ROOT/0001-imgui-allow-flags-in-button-usage.patch
popd

cmake -S . -B build
cp ./imgui.ini ./build/imgui.ini
